sudo: required
services:
 - docker
before_install:  gem install bundler --pre
 - docker build -t pandiec/docker-react -f Dockerfile.dev .
script:
 - docker run pandiec/docker-react npm run test -- --coverage
