sudo: required
services:
 - docker
before_install: 
 - travis_wait docker build -t pandiec/docker-react -f Dockerfile.dev .
script:
 - travis_wait docker run pandiec/docker-react npm run test -- --coverage
